"use client";
import { useState } from "react";

const homes=[
  ["Austin","Space for the life you are building","Homes with light, character, and a sense of possibility.","https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=1200&q=85"],
  ["Dallas","City-connected, beautifully grounded","A considered base for work, family, and everything between.","https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?auto=format&fit=crop&w=1200&q=85"],
  ["Hill Country","A little more room to breathe","A slower setting with the essentials still close at hand.","https://images.unsplash.com/photo-1600566753086-00f18fb6b3ea?auto=format&fit=crop&w=1200&q=85"]
];
const faqs=[
 ["What happens after I enquire?","Taha starts with a short, useful conversation about the way you want to live, then curates a focused next step."],
 ["Can I start before I am ready to buy?","Yes. You can explore early, understand the local market, and set the right pace for your move."],
 ["Which Texas areas do you cover?","This sample experience focuses on Austin, Dallas, and Hill Country. It can be adapted to Taha’s actual service areas."]
];

export default function Home(){
 const [area,setArea]=useState("All Texas"),[open,setOpen]=useState(0),[sent,setSent]=useState(false);
 const shown=homes.filter(x=>area==="All Texas"||x[0]===area);
 return <main>
  <section className="hero" id="home"><nav className="wrap nav"><a className="logo" href="#home"><b>T</b> TAHA <i>PROPERTY</i></a><div><a href="#homes">Homes</a><a href="#approach">Approach</a><a href="#contact">Contact</a><a className="pill" href="#start">Find your home ↗</a></div></nav><div className="wrap heroCopy"><p className="label light">Texas real estate, considered</p><h1>Find a home that<br/><em>feels like yours.</em></h1><div className="heroFoot"><p>Personal guidance for buyers looking for more than a listing — throughout Texas.</p><a className="circle" href="#start">Start your search <b>↘</b></a></div></div><small>[ Homepage main visual — Texas home at golden hour ]</small></section>
  <section className="wrap intro" id="approach"><p className="label">A better way to look</p><div><h2>Good homes are about<br/>more than square feet.</h2><aside><p>They are about the morning light, the neighborhood rhythm, and how a place fits your next chapter. Taha helps buyers make confident, well-informed choices — without the noise.</p><a href="#start">Meet your next move →</a></aside></div></section>
  <section className="listing" id="homes"><div className="wrap"><header><div><p className="label">Explore by lifestyle</p><h2>Start somewhere<br/><em>that feels right.</em></h2></div><nav className="filters">{["All Texas","Austin","Dallas","Hill Country"].map(x=><button onClick={()=>setArea(x)} className={area===x?"selected":""} key={x}>{x}</button>)}</nav></header><div className="cards">{shown.map(x=><article key={x[0]}><div className="photo"><img src={x[3]} alt={x[1]}/><span>{x[0]}</span></div><h3>{x[1]}</h3><p>{x[2]}</p><a href="#start">Explore ↗</a></article>)}</div></div></section>
  <section className="wrap process"><div className="interior"><img src="https://images.unsplash.com/photo-1600607687920-4e2a09cf159d?auto=format&fit=crop&w=1500&q=85" alt="Warm welcoming interior"/><small>[ Lifestyle interior visual ]</small></div><div><p className="label">A personal search</p><h2>A clear path,<br/><em>at your pace.</em></h2><ol><li><b>01</b><span><h3>Share your picture</h3><p>Tell us what would make a home feel right: area, budget, timeline, and non-negotiables.</p></span></li><li><b>02</b><span><h3>See the real fit</h3><p>Receive a thoughtful shortlist, clear local context, and honest guidance on each option.</p></span></li><li><b>03</b><span><h3>Move with confidence</h3><p>From first viewing to keys in hand, keep every next step simple and well supported.</p></span></li></ol></div></section>
  <section className="quote"><div className="wrap"><b>“</b><blockquote>Buying a home should feel<br/>exciting — <em>not overwhelming.</em></blockquote><p>THAT IS WHY EVERY SEARCH BEGINS WITH LISTENING.</p></div></section>
  <section className="wrap start" id="start"><div><p className="label">Begin your search</p><h2>Let’s find your<br/><em>right next place.</em></h2><p>A few details are enough to start a smarter conversation.</p></div><form onSubmit={e=>{e.preventDefault();setSent(true)}}>{sent?<div className="thanks"><b>✓</b><h3>You are on the list.</h3><p>Thank you. Taha will be in touch to learn more about your search.</p><button type="button" onClick={()=>setSent(false)}>Send another enquiry</button></div>:<><label>Your name<input required placeholder="Your name"/></label><label>Email address<input required type="email" placeholder="you@email.com"/></label><label>What are you looking for?<select required defaultValue=""><option value="" disabled>Select a home type</option><option>Family home</option><option>Condo / townhome</option><option>Land or ranch</option><option>Investment property</option><option>Still exploring</option></select></label><button>Start the conversation <span>↗</span></button><small>No pressure. Your details stay private.</small></>}</form></section>
  <section className="wrap faq"><div><p className="label">Common questions</p><h2>Helpful from<br/>the very start.</h2></div><div>{faqs.map((x,i)=><article key={x[0]}><button onClick={()=>setOpen(open===i?-1:i)}><span>{x[0]}</span><b>{open===i?"−":"+"}</b></button>{open===i&&<p>{x[1]}</p>}</article>)}</div></section>
  <footer id="contact"><div className="wrap"><a className="logo" href="#home"><b>T</b> TAHA <i>PROPERTY</i></a><h2>Texas homes.<br/><em>Thoughtfully found.</em></h2><a className="circle" href="#start">Find your home ↗</a></div><div className="wrap legal"><span>© 2026 Taha Property</span><a href="mailto:hello@tahaproperty.com">hello@tahaproperty.com</a><span>Texas, United States</span></div></footer>
 </main>
}
